name: Build Static Site

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITE_HOST: ${{ vars.SITE_HOST }}
      THOR_SILENCE_DEPRECATION: 1

    steps:
      - uses: actions/checkout@v1
      # ---------------------------------------------------------------
      # Ruby
      # ---------------------------------------------------------------
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.0
      - name: Ruby Version
        run: |
          ruby -v
      - name: Setup Ruby Dependencies
        run: |
          gem update bundler
          bundle install --jobs 4 --retry 3
      - name: Test Ruby Dependencies
        run: |
          bundle exec rake -T
      # ---------------------------------------------------------------
      # Javascript
      # ---------------------------------------------------------------
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.6.0
      - name: Node Version
        run: |
          node --version
      - name: Install Yarn
        run: |
          npm install --global yarn
      - name: Yarn Version
        run: |
          yarn --version
      - name: Install Dependencies
        run: |
          yarn install
      # ---------------------------------------------------------------
      # Webpack
      # ---------------------------------------------------------------
      - name: Build Webpack File
        run: |
          bundle exec rake webpack:build:production

      - name: Build Site
        run: |
          export TERM=xterm

          bundle exec middleman build -e production --verbose
      # ---------------------------------------------------------------
      # Quality
      # ---------------------------------------------------------------
      - name: Rubocop
        run: |
          bundle exec rubocop

      - name: ESLint
        run: |
          yarn run lint:js

      - name: StyleLint
        run: |
          yarn run lint:css
