name: SECURITY

# gitleaks detect \
#   --source=. \
#   --redact \
#   --verbose > tmp/gitleaks-output.txt 2>&1

on:
  pull_request:

jobs:
  security_leaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect \
            --source=. \
            --redact \
            --exit-code=1
